// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

// Auth actions
export const AUTH_INITIALIZATION_DONE = 'AUTH_INITIALIZATION_DONE';
export const AUTH_LOGGED_IN_SUCCESS = 'AUTH_LOGGED_IN_SUCCESS';
export const AUTH_LOGGED_OUT_SUCCESS = 'AUTH_LOGGED_OUT_SUCCESS';

// User actions
export const USER_CREATED_SUCCESS = 'USER_CREATED_SUCCESS';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_IS_ADMIN_SUCCESS = 'USER_IS_ADMIN_SUCCESS';

// Chat actions
export const CHAT_MESSAGE_LISTENING_STARTED = 'CHAT_MESSAGE_LISTENING_STARTED';
export const CHAT_MESSAGE_RECEIVED_SUCCESS = 'CHAT_MESSAGE_RECEIVED_SUCCESS';
export const CHAT_MESSAGE_POST_SUCCESS = 'CHAT_MESSAGE_POST_SUCCESS';
export const CHAT_ROOM_LISTENING_STARTED = 'CHAT_ROOM_LISTENING_STARTED';
export const CHAT_ROOM_RECEIVED_SUCCESS = 'CHAT_ROOM_RECEIVED_SUCCESS';
export const CHAT_ROOM_JOIN_SUCCESS = 'CHAT_ROOM_JOIN_SUCCESS';
